// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Coderlane/minecraft-sidecart/db (interfaces: Database)

// Package db is a generated GoMock package.
package db

import (
	context "context"
	server "github.com/Coderlane/minecraft-sidecart/server"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDatabase is a mock of Database interface
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// CreateServer mocks base method
func (m *MockDatabase) CreateServer(arg0 context.Context, arg1 server.Type, arg2 interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServer indicates an expected call of CreateServer
func (mr *MockDatabaseMockRecorder) CreateServer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockDatabase)(nil).CreateServer), arg0, arg1, arg2)
}

// UpdateServerInfo mocks base method
func (m *MockDatabase) UpdateServerInfo(arg0 context.Context, arg1 string, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServerInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServerInfo indicates an expected call of UpdateServerInfo
func (mr *MockDatabaseMockRecorder) UpdateServerInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServerInfo", reflect.TypeOf((*MockDatabase)(nil).UpdateServerInfo), arg0, arg1, arg2)
}
