name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  units:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Add private token
      run:  git config --global url."https://${{ secrets.GO_TOKEN }}:x-oauth-basic@github.com/Coderlane".insteadOf "https://github.com/Coderlane"

    - name: Test
      run: go test -v -coverprofile=coverage.out ./...
      env:
        GOPRIVATE: github.com/Coderlane/*

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
       token: ${{ secrets.CODECOV_TOKEN }}
       fail_ci_if_error: true
